import React from "react";
import Head from "next/head";
import { Box, Container, Flex, Heading, Text } from "@chakra-ui/react";

const IndexPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>PMS : Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container overflowY="auto" maxW="4xl">
        <Heading mt={{ base: "0", md: "35px" }} size="md" fontWeight="semibold">
          Welcome User
        </Heading>

        <Flex
          direction={{ base: "column", md: "row" }}
          w="100%"
          justify="center"
          alignItems="center"
          mt="50px"
        >
          <Box w={{ base: "100%", md: "50%" }} pr="7px">
            <Text>Admitted patient count</Text>

            <Box
              height="200px"
              backgroundColor="white"
              shadow="sm"
              borderRadius="lg"
              mt="25px"
            ></Box>
          </Box>
          <Box w={{ base: "100%", md: "50%" }} pl="7px">
            <Text>Patient History</Text>

            <Box
              height="200px"
              backgroundColor="white"
              shadow="sm"
              borderRadius="lg"
              mt="25px"
            ></Box>
          </Box>
        </Flex>

        <Box mt="25px">
          <Text>Patient Table</Text>

          <Box
            height="200px"
            backgroundColor="white"
            shadow="sm"
            borderRadius="lg"
            mt="25px"
          ></Box>
        </Box>
      </Container>
    </>
  );
};

export default IndexPage;
